name: Android CI
on: workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-20.04  # Използваме по-стара операционна система за съвместимост
    steps:
      - uses: actions/checkout@v2
      
      - name: set up JDK 11  # Старите проекти работят по-добре с Java 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Build with Gradle
        run: |
          chmod +x gradlew
          ./gradlew assembleDebug --no-daemon -Pandroid.skipAssistant=true
          
      - name: Upload APK
        uses: actions/upload-artifact@v2
        with:
          name: BlackBox-Old-Build
          path: app/build/outputs/apk/debug/*.apk
