name: Android CI

on:
  workflow_dispatch:

jobs:
  build:
    name: Build Apk
    runs-on: ubuntu-latest
    env:
      # Това принуждава GitHub да използва по-нова версия на Node, за да изчезнат грешките
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true 
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          # Премахваме кеша временно, за да сме сигурни, че няма стари грешни библиотеки
          cache: none 

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        # Добавяме --info, за да видим точно кой файл гърми
        run: ./gradlew clean assembleDebug --stacktrace --info

      - name: Upload Apk
        uses: actions/upload-artifact@v4
        with:
          name: BlackBox-Aim-Assistant
          path: app/build/outputs/apk/debug/*.apk
